### ISSUE TITLE
get handler with Symbol

### ISSUE THREAD

**Issue by soubok** [Swatinem/proxy#1]
I fail to use the Proxy get handler with a ES6 Symbol as property name:

```
var Proxy = require('harmony-proxy');

var p = new Proxy(Object.create(null), {

    get: function(target, property) {

        return 'bar';
    }
});


console.log( p['foo'] ); // prints bar
console.log( p[Symbol('fooSym')] ); // prints undefined
```

**Comment by Swatinem** [comment]
This is basically a shim to expose the old proxy interface as it is implemented in v8 with the same interface as the new proxy interface.

So I don’t think this is something that can be fixed. And either way, I hope v8 will implement ES2015 proxies soon natively.
