### ISSUE TITLE
Error when trying to call empty handler Proxy on Function

### ISSUE THREAD

**Issue by neico** [Swatinem/proxy#2]
Essentially the second argument of Proxy.createFunction is required ( call / apply ) while construct isn't.
But the direct proxies API explicitly states that every trap is optional, so [index.js#L98](../blob/master/index.js#L98) needs to be adjusted to allow the apply trap to be optional.

**Comment by Swatinem** [comment]
Are you willing to provide a patch?

tbh, I haven’t touched this code in a _long_ time, and I would rather wait for native support to solve all the issues.
