### ISSUE TITLE
error message suggesting "node --harmony" is incorrect

### ISSUE THREAD

**Issue by smurp** [Swatinem/proxy#8]
Starting `node --harmony` (at least with nodejs 5.10.1 anyway) leaves `typeof Proxy` producing `undefined` and hence the error message that `harmony-proxy` produces under these circumstances

```
'Native proxies not enabled. use `node --harmony` or `node --harmony-proxies`'
```

suggesting the use of `node --harmony` is misleading.

**Comment by Swatinem** [comment]
fixed in `1.0.1`, thanks. Also, I can’t wait for real native promises :-)
